export const GALLERY_FETCH_SUCCESS = 'GALLERY_FETCH_SUCCESS'
export const SET_CURRENT_PAGE_INDEX = 'SET_CURRENT_PAGE_INDEX'
export const ABOUT_FETCH_SUCCESS = 'ABOUT_FETCH_SUCCESS'
export const HERO_FETCH_SUCCESS = 'HERO_FETCH_SUCCESS '
export const MYSQL_HOST = '147.139.170.168'
export const MYSQL_PORT = 33066
export const MYSQL_USER = "dana"
export const MYSQL_PASS = "web@dana.id"

export default {
  GALLERY_FETCH_SUCCESS,
  SET_CURRENT_PAGE_INDEX,
  ABOUT_FETCH_SUCCESS,
  HERO_FETCH_SUCCESS,
  MYSQL_HOST,
  MYSQL_PORT,
  MYSQL_USER,
  MYSQL_PASS
}